name: Push - Run Yarn Tests
'on':
    push:
        branches:
            - '**'
jobs:
    unit_tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2.3.4
              name: Checkout
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn config get cache-folder)"
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Run Yarn
              run: yarn
            - name: Run Yarn Tests
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: yarn test-ci
            - uses: IgnusG/jest-report-action@v2.3.3
              if: always() # Or use "continue-on-error: true" in previous test step
              with:
                  access-token: ${{ secrets.GITHUB_TOKEN }}
